name: Pull Request Comment Handler

on:
  issue_comment:
    types: [ created ]

jobs:
  pullRequestCommentHandler:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/verify')
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
