name: Issue Hander

on:
  issues:
    types: [ opened, labeled ]

jobs:
  issueHandler:
    if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
