name: Handle Pull Request Comments

on:
  issue_comment:
    types: [ created ]

jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: PullRequestHandler
      uses: ScoopInstaller/GithubActions@main
      if: startsWith(github.event.comment.body, '/verify')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
