name: Handle Pull Requests

on:
  pull_request:
    types: [ opened ]

jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: PullRequestHandler
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
