name: Pull Request Handler

on:
  pull_request:
    types: [ opened ]

jobs:
  pullRequestHandler:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
